---
name: ğŸ·ï¸ Verify PR Labels

on:
  pull_request_target:
    types: ["opened", "labeled", "unlabeled", "synchronize"]
  workflow_dispatch: {}

jobs:
  labels:
    name: "ğŸ·ï¸"
    uses: z-shell/.github/.github/workflows/pr-labels.yml@main
